let incident = null;
let currentPosition = null;
let mediaRecorder = null;
let mediaStream = null;
let recordedChunks = [];
const profile = JSON.parse(localStorage.getItem("vayuProfile") || "null");
const incidentId = () => `VB-SOS-${Date.now().toString().slice(-8)}`;
const setText = (id, value) => { document.getElementById(id).textContent = value; };
function updateIncident() { if (!incident) return; setText("incident-id", incident.id); setText("admin-status", incident.adminAlert ? "Sent" : "Not sent"); setText("contact-status", incident.contactAlert ? "Queued" : "Not notified"); setText("gps-status", incident.location ? "Captured" : "Not shared"); setText("recording-status", incident.recording ? "Saved" : "Not started"); localStorage.setItem("vayuEmergencyIncident", JSON.stringify(incident)); }
function captureGps() { return new Promise((resolve) => { if (!navigator.geolocation) { resolve(false); return; } navigator.geolocation.getCurrentPosition((position) => { currentPosition = { latitude: position.coords.latitude, longitude: position.coords.longitude, accuracy: position.coords.accuracy, capturedAt: new Date().toISOString() }; if (incident) incident.location = currentPosition; resolve(true); }, () => resolve(false), { enableHighAccuracy: true, timeout: 10000 }); }); }
async function sendIncidentToDjango() { try { const response = await fetch("/api/emergency/incidents/", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ incident_id: incident.id, user_identifier: localStorage.getItem("vayuLoggedInUser") || "guest", location: incident.location, emergency_contacts: { one: profile?.["emergency-one"] || "", two: profile?.["emergency-two"] || "" }, camera_enabled: Boolean(mediaStream), microphone_enabled: Boolean(mediaStream) }) }); if (!response.ok) throw new Error("API request failed"); const result = await response.json(); incident.adminEmailStatus = result.admin_email_status; incident.apiSaved = true; incident.locationLink = result.location_link; setText("admin-status", `Saved · ${result.admin_email_status}`); setText("incident-message", `Django incident ${result.incident_id} saved. Admin email: ${result.admin_email_status}. SMS: ${result.sms_status}.`); updateIncident(); } catch (error) { setText("incident-message", "Django API is unavailable. The incident remains saved locally until the server is running."); updateIncident(); } }
async function activateSOS() { incident = { id: incidentId(), createdAt: new Date().toISOString(), adminAlert: true, contactAlert: false, location: null, recording: false }; const gpsCaptured = await captureGps(); setText("sos-status", gpsCaptured ? "SOS active · GPS captured · Sending admin alert..." : "SOS active · GPS permission is still needed."); updateIncident(); await sendIncidentToDjango(); }
document.getElementById("start-sos").addEventListener("click", () => document.getElementById("sos-confirm").showModal());
document.getElementById("cancel-sos").addEventListener("click", () => document.getElementById("sos-confirm").close());
document.getElementById("confirm-sos").addEventListener("click", async () => { document.getElementById("sos-confirm").close(); await activateSOS(); });
document.getElementById("share-location").addEventListener("click", async () => { if (!incident) incident = { id: incidentId(), createdAt: new Date().toISOString(), adminAlert: true, contactAlert: false, location: null, recording: false }; const captured = await captureGps(); setText("gps-status", captured ? "Captured" : "Permission needed"); setText("incident-message", captured ? "Location attached to the incident." : "Allow location access to attach GPS."); updateIncident(); if (captured && !incident.apiSaved) await sendIncidentToDjango(); });
document.getElementById("notify-contacts").addEventListener("click", () => { if (!incident) incident = { id: incidentId(), createdAt: new Date().toISOString(), adminAlert: false, contactAlert: false, location: currentPosition, recording: false }; incident.contactAlert = true; const contacts = [profile?.["emergency-one"], profile?.["emergency-two"]].filter(Boolean).join(" · "); setText("incident-message", contacts ? `Emergency contact alert queued for ${contacts}.` : "Save emergency contacts in your profile first."); updateIncident(); });
document.getElementById("enable-media").addEventListener("click", async () => { try { mediaStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true }); document.getElementById("incident-preview").srcObject = mediaStream; document.getElementById("start-recording").disabled = false; setText("media-status", "Camera and microphone ready."); } catch (error) { setText("media-status", "Camera or microphone permission was not granted."); } });
document.getElementById("start-recording").addEventListener("click", () => { if (!mediaStream) return; recordedChunks = []; mediaRecorder = new MediaRecorder(mediaStream); mediaRecorder.ondataavailable = (event) => { if (event.data.size) recordedChunks.push(event.data); }; mediaRecorder.onstop = async () => { const recording = new Blob(recordedChunks, { type: "video/webm" }); incident = incident || { id: incidentId(), createdAt: new Date().toISOString(), adminAlert: false, contactAlert: false, location: currentPosition }; incident.recording = { type: recording.type, size: recording.size, savedAt: new Date().toISOString() }; if (incident.apiSaved) { const formData = new FormData(); formData.append("recording", recording, `${incident.id}.webm`); formData.append("camera_enabled", "true"); formData.append("microphone_enabled", "true"); await fetch(`/api/emergency/incidents/${incident.id}/recording/`, { method: "POST", body: formData }); } setText("media-status", "Incident recording saved locally and uploaded when the API is available."); updateIncident(); }; mediaRecorder.start(); document.getElementById("start-recording").disabled = true; document.getElementById("stop-recording").disabled = false; setText("recording-status", "Recording"); });
document.getElementById("stop-recording").addEventListener("click", () => { if (mediaRecorder && mediaRecorder.state !== "inactive") mediaRecorder.stop(); document.getElementById("start-recording").disabled = false; document.getElementById("stop-recording").disabled = true; });
