# Generated by Django 6.1.1 on 2026-09-23 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=32, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved')], default='active', max_length=16)),
                ('user_identifier', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_accuracy', models.FloatField(blank=True, null=True)),
                ('emergency_contact_1', models.CharField(blank=True, max_length=255)),
                ('emergency_contact_2', models.CharField(blank=True, max_length=255)),
                ('admin_email', models.EmailField(blank=True, max_length=254)),
                ('admin_phone', models.CharField(blank=True, max_length=20)),
                ('admin_email_status', models.CharField(default='queued', max_length=32)),
                ('contact_alert_status', models.CharField(default='queued', max_length=32)),
                ('sms_status', models.CharField(default='provider_not_configured', max_length=32)),
                ('call_requested', models.BooleanField(default=False)),
                ('camera_enabled', models.BooleanField(default=False)),
                ('microphone_enabled', models.BooleanField(default=False)),
                ('recording', models.FileField(blank=True, null=True, upload_to='emergency_recordings/')),
                ('recording_size', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
